services:
  postgres:
    image: postgres:15-alpine
    container_name: fathers-math-db
    environment:
      POSTGRES_DB: fathers_math
      POSTGRES_USER: fathers_math_user
      POSTGRES_PASSWORD: fathers_math_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/backups:/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fathers_math_user -d fathers_math"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
